[ALPS11034563] fix GPU build error
[Description]
kernel-6.1/include/linux/minmax.h:315:9: error: MAX macro redefined [-Werror,-Wmacro-redefined]
#define MAX(a, b) __cmp(max, a, b)
        ^
vendor/mediatek/kernel_modules/gpu/mt6897/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/mali_malisw.h:53:9: note: previous definition is here
#define MAX(x, y)       ((x) < (y) ? (y) : (x))

[Test]
Build Pass

MTK-Commit-Id: ce712aee4fb33318e38c44a08e6cbc2bdcaa586a

(cherry picked from commit 40cce2119ba5be704b6fb5d106944a7f5517bb1c)
Signed-off-by: Liangjun Kuang <ot_liangjun.kuang@mediatek.com>
CR-Id: ALPS11034563
Feature: Kernel SI Operation
Change-Id: Ia79a4e05d41e76639e4086226e066b504417b4a6