[ALPS11034563] fix bt build error
[Description]
vendor/mediatek/kernel_modules/connectivity/bt/mt66xx/include/btmtk_define.h:100:9: error: MIN macro redefined [-Werror,-Wmacro-redefined]
#define MIN(a, b) (((a) < (b)) ? (a) : (b))
        ^
kernel-6.1/include/linux/minmax.h:314:9: note: previous definition is here
#define MIN(a, b) __cmp(min, a, b)

[Test]
Build pass

MTK-Commit-Id: 8de9d9a81dd222546776cab454ee8ea61ac0267f

(cherry picked from commit e3ab4ed9a0f2785ec43b6d2a4ebdfac31c9ae437)
Signed-off-by: Liangjun Kuang <ot_liangjun.kuang@mediatek.com>
CR-Id: ALPS11034563
Feature: Kernel SI Operation
Change-Id: Ia092e8a8e2c96b9e4b00c735f1c1747b0f0a2ab4